config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  get "/users/profile", controller: :users, action: :profile, as: :profile
  put "/users/profile", controller: :users, action: :update_profile, as: :update_profile
  get '/settings', controller: :settings, action: :index, as: :settings
  get '/closings', controller: :closings, action: :index, as: :closings
  get '/reauth/:token', controller: :reauth, action: :reauth
  scope "/admin" do
    get "/", controller: :admin, action: :index, as: :admin_index
    resources :users, as: :admin_users
    resources :appointment_types, as: :admin_appointment_types
    resources :appointments, as: :admin_appointments
    resources :announcements, as: :admin_announcements
    resources :settings, as: :admin_settings
    resources :closings, only: [:create, :update, :destroy], as: :admin_closings
    authenticate :user, lambda { |u| u.admin_or_staff? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  root 'appointments#index'

  resources :appointment_types, only: [:index, :show], format: :json

  resources :appointments do
    collection do
      get :stage
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include DateParse

  scope :recent, -> { where("end_date > ?", 1.month.ago) }
  scope :show, ->(kind) { where("end_date >= ? AND (kind = ? OR kind = ?)", Time.now, kind, Announcement.kinds[:both]) }

  reformat_date :end_date, "%m/%d/%Y %H:%M %p"

  enum :kind, {patient: 0, staff: 1, both: 2}

  validates_presence_of :name
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.recent
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to admin_announcement_url(@announcement), notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to admin_announcement_url(@announcement), notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_announcement_url(@announcement) }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to admin_announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:name, :kind, :content, :end_date)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for([:admin, @announcement], html: {class: 'form-horizontal'}) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-group-lg">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
      <span class="help-block"><i>Just a label for you, not shown to the users</i></span>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :content, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: 'form-control' %>
      <span class="help-block"><i>Try to keep this short or users may not read it!</i></span>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :kind, 'Shown to', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :kind, options_for_select(Announcement.kinds.keys.map {|k| [k.titleize, k]}, f.object.kind), {}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :end_date, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <div id="end_date_container" class="input-group date">
        <%= f.text_field :end_date, class: 'form-control', value: f.object.end_date.try(:strftime, "%m/%d/%Y %I:%M %p"), data: {datetime: true} %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <span class="help-block"><i>When to stop displaying to the users</i></span>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

app/views/announcements/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h1>Listing Recent Announcements</h1>
  </div>
  <div class+"col-lg-4">
    <%= link_to 'New Announcement', new_admin_announcement_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Shown to</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td>
          <% if announcement.staff? %>
            <span class="glyphicon glyphicon-eye-open"></span>
          <% end %>
          <%= announcement.name %>
        </td>
        <td><%= announcement.kind.to_s.titleize %></td>
        <td><%= time_ago_in_words(announcement.end_date) %> <%= announcement.end_date >= Time.now ? 'from now' : 'ago' %> (<%= announcement.end_date.strftime("%m/%d/%Y %I:%m %p") %>)</td>
        <td><%= link_to 'Show', admin_announcement_path(announcement) %></td>
        <td><%= link_to 'Edit', edit_admin_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', admin_announcement_path(announcement), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_announcements_path %>

app/views/announcements/show.html.erb
<div id="announcement" class="row well">
  <div class="col-sm-12">
    <h2>
      <%= @announcement.name %> <small>(<%= @announcement.end_date.try(:strftime, "%m/%d/%Y %I:%m %p") || 'No date set' %>)</small>
      <%= link_to 'Edit', edit_admin_announcement_path(@announcement), class: 'btn btn-primary' %>
    </h2>
  </div>
  <div class="col-sm-12">
    <h4><%= @announcement.content %></h4>
  </div>
</div>