config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  get "/users/profile", controller: :users, action: :profile, as: :profile
  put "/users/profile", controller: :users, action: :update_profile, as: :update_profile
  get '/settings', controller: :settings, action: :index, as: :settings
  get '/closings', controller: :closings, action: :index, as: :closings
  get '/reauth/:token', controller: :reauth, action: :reauth
  scope "/admin" do
    get "/", controller: :admin, action: :index, as: :admin_index
    resources :users, as: :admin_users
    resources :appointment_types, as: :admin_appointment_types
    resources :appointments, as: :admin_appointments
    resources :announcements, as: :admin_announcements
    resources :settings, as: :admin_settings
    resources :closings, only: [:create, :update, :destroy], as: :admin_closings
    authenticate :user, lambda { |u| u.admin_or_staff? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  root 'appointments#index'

  resources :appointment_types, only: [:index, :show], format: :json

  resources :appointments do
    collection do
      get :stage
    end
  end

end

app/controllers/appointment_types_controller.rb
class AppointmentTypesController < ApplicationController
  before_action :authenticate_user!, unless: :index
  before_action :require_admin!, unless: :index

  before_action :set_appointment_type, only: [:show, :edit, :update, :destroy]

  # GET /appointment_types
  # GET /appointment_types.json
  def index
    @appointment_types = AppointmentType.all
  end

  # GET /appointment_types/1
  # GET /appointment_types/1.json
  def show
  end

  # GET /appointment_types/new
  def new
    @appointment_type = AppointmentType.new
  end

  # GET /appointment_types/1/edit
  def edit
  end

  # POST /appointment_types
  # POST /appointment_types.json
  def create
    @appointment_type = AppointmentType.new(appointment_type_params)

    respond_to do |format|
      if @appointment_type.save
        format.html { redirect_to @appointment_type, notice: 'Appointment type was successfully created.' }
        format.json { render :show, status: :created, location: @appointment_type }
      else
        format.html { render :new }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_types/1
  # PATCH/PUT /appointment_types/1.json
  def update
    respond_to do |format|
      if @appointment_type.update(appointment_type_params)
        format.html { redirect_to admin_appointment_types_path, notice: 'Appointment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment_type }
      else
        format.html { render :edit }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_types/1
  # DELETE /appointment_types/1.json
  def destroy
    @appointment_type.destroy
    respond_to do |format|
      format.html { redirect_to appointment_types_url, notice: 'Appointment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment_type
      @appointment_type = AppointmentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_type_params
      params.require(:appointment_type).permit(:name, :duration, :prep_duration, :post_duration, :color_class, :group, :group_time_per_person, :text_color, :overlap, :description)
    end
end

app/helpers/appointment_types_helper.rb
module AppointmentTypesHelper

  COLORS = %w(aqua black blue fuchsia gray green lime maroon navy olive orange purple red silver teal white yellow).
          map {|c| {c.titleize => c}}.reduce(&:merge)

  def appointment_type_colors
    COLORS
  end

end

app/views/appointment_types/_form.html.erb
<%= form_for([:admin, @appointment_type], html: {class: 'form-horizontal'}) do |f| %>
  <% if @appointment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment_type.errors.count, "error") %> prohibited this appointment_type from being saved:</h2>

      <ul>
      <% @appointment_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-group-lg">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :duration, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.number_field :duration, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :prep_duration, class: 'col-sm-offset-1 col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.number_field :prep_duration, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :post_duration, class: 'col-sm-offset-1 col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.number_field :post_duration, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :overlap, 'Allow Overlap', class: 'col-sm-offset-1 col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.select :overlap, options_for_select({"Yes" => 1, "No" => 0}, selected: @appointment_type.overlap ? 1 : 0), {}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :group, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :group, options_for_select({"Yes" => 1, "No" => 0}, selected: @appointment_type.group ? 1 : 0), {}, class: 'form-control', onchange: 'javascript:$("#group-time-per-person").toggleClass("hidden")' %>
    </div>
  </div>
  <div id="group-time-per-person" class="form-group form-group-lg <%= "hidden" unless @appointment_type.group %>">
    <%= f.label :group_time_per_person, class: 'col-sm-offset-1 col-sm-2 control-label' %>
    <div class="col-sm-9">
      <%= f.number_field :group_time_per_person, class: 'form-control', value: @appointment_type.group_time_per_person %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :color_class, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :color_class, options_for_select(appointment_type_colors, selected: @appointment_type.color_class), {}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :text_color, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :text_color, options_for_select(appointment_type_colors, selected: @appointment_type.text_color), {}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: 'form-control', placeholder: 'Keep it short! This will be displayed in a tooltip.' %>
      <small>
        Be sure not to write too much. The full width of this box takes up 3-4 lines long in the tooltip. Any more than that and users are unlikely to read it.
      </small>
    </div>
  </div>
  <div class="form-group form-group-lg">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/appointment_types/edit.html.erb
<h1>Editing <%= @appointment_type.name %></h1>

<%= render 'form' %>

app/views/appointment_types/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h1>Listing All Appointment Types</h1>
  </div>
  <div class+"col-lg-4">
    <%= link_to 'New Appointment Type', new_admin_appointment_type_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Group</th>
      <th>Prep duration</th>
      <th>Post duration</th>
      <th>Color class</th>
      <th>Text Color</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment_types.each do |appointment_type| %>
      <tr>
        <td><%= link_to appointment_type.name, appointment_type %></td>
        <td><%= appointment_type.duration %> <%= appointment_type.overlap? ? "w/ overlap" : "" %></td>
        <td><%= appointment_type.group? ? "+#{appointment_type.group_time_per_person} mins/person" : 'No' %></td>
        <td><%= appointment_type.prep_duration %></td>
        <td><%= appointment_type.post_duration %></td>
        <td><%= appointment_type.color_class %></td>
        <td><%= appointment_type.text_color %></td>
        <td><%= link_to content_tag(:i, 'Edit', class: 'glyphicon glyphicon-edit'), edit_admin_appointment_type_path(appointment_type) %></td>
        <td><%= link_to content_tag(:i, 'Remove', class: 'glyphicon glyphicon-trash'), admin_appointment_type_path(appointment_type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointment_types/new.html.erb
<h1>New appointment_type</h1>

<%= render 'form' %>

<%= link_to 'Back', appointment_types_path %>

app/views/appointment_types/show.html.erb
<div class="well">
  <div class="row">
    <div class="col-sm-10">
      <h3>
        <%= @appointment_type.name %> <small>(<%= @appointment_type.duration %> mins <%= @appointment_type.overlap? ? "w/ overlap" : "" %><%= @appointment_type.group? ? " +#{@appointment_type.group_time_per_person} mins/person" : 'Group not allowed' %>)</small>
        <%= link_to 'Edit', edit_admin_appointment_type_path(@appointment_type), class: 'btn btn-primary pull-right' %>
      </h3>
    </div>
    <div class="col-sm-2 small">
      Prep Time: <%= @appointment_type.prep_duration %><br/>
      Post Appt Time: <%= @appointment_type.post_duration %><br/>
      Background Color: <%= @appointment_type.color_class %><br/>
      Text Color: <%= @appointment_type.text_color %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h4>
        <%= @appointment_type.description %>
      </h4>
    </div>
  </div>
</div>

<div class="">

</div>