config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  get "/users/profile", controller: :users, action: :profile, as: :profile
  put "/users/profile", controller: :users, action: :update_profile, as: :update_profile
  get '/settings', controller: :settings, action: :index, as: :settings
  get '/closings', controller: :closings, action: :index, as: :closings
  get '/reauth/:token', controller: :reauth, action: :reauth
  scope "/admin" do
    get "/", controller: :admin, action: :index, as: :admin_index
    resources :users, as: :admin_users
    resources :appointment_types, as: :admin_appointment_types
    resources :appointments, as: :admin_appointments
    resources :announcements, as: :admin_announcements
    resources :settings, as: :admin_settings
    resources :closings, only: [:create, :update, :destroy], as: :admin_closings
    authenticate :user, lambda { |u| u.admin_or_staff? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  root 'appointments#index'

  resources :appointment_types, only: [:index, :show], format: :json

  resources :appointments do
    collection do
      get :stage
    end
  end

end

app/views/admin/index.html.erb
<br/>
<div class="well">
  <div class="bs-glyphicons">
    <ul class="bs-glyphicons-list">
      <li>
        <%= link_to admin_users_path do %>
          <span class="glyphicon glyphicon-user"></span>
          <span class="glyphicon-class">Patient Lookup</span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_appointment_types_path do %>
          <span class="glyphicon glyphicon-tags"></span>
          <span class="glyphicon-class">Appointment Types</span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_announcements_path do %>
          <span class="glyphicon glyphicon-bullhorn"></span>
          <span class="glyphicon-class">Announcements</span>
        <% end %>
      </li>
      <li class="admin-pane-row"></li>
      <li class="admin-pane-row">
        <%= link_to admin_settings_path do %>
          <span class="glyphicon glyphicon-cog"></span>
          <span class="glyphicon-class">Settings</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>