config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  get "/users/profile", controller: :users, action: :profile, as: :profile
  put "/users/profile", controller: :users, action: :update_profile, as: :update_profile
  get '/settings', controller: :settings, action: :index, as: :settings
  get '/closings', controller: :closings, action: :index, as: :closings
  get '/reauth/:token', controller: :reauth, action: :reauth
  scope "/admin" do
    get "/", controller: :admin, action: :index, as: :admin_index
    resources :users, as: :admin_users
    resources :appointment_types, as: :admin_appointment_types
    resources :appointments, as: :admin_appointments
    resources :announcements, as: :admin_announcements
    resources :settings, as: :admin_settings
    resources :closings, only: [:create, :update, :destroy], as: :admin_closings
    authenticate :user, lambda { |u| u.admin_or_staff? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  root 'appointments#index'

  resources :appointment_types, only: [:index, :show], format: :json

  resources :appointments do
    collection do
      get :stage
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include DateParse
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :appointments
  has_many :phones
  has_many :addresses
  validates :phones, presence: true
  validates :addresses, presence: true
  validates_presence_of :first, :last, :dob, :gender
  enum :role, {patient: 0, staff: 1, admin: 2}
  enum :gender, {male: 0, female: 1}
  #reformat_date :dob, "%m/%d/%Y"

  accepts_nested_attributes_for :phones, :addresses, allow_destroy: true

  # Hack to stop saving '' in the email field when no email address is supplied
  before_save do |user|
    user.email = nil if user.email.blank?
  end

  scope :search, ->(q) {
    date = ['/', '-', '.'].reduce(nil) {|final,sep| final || Date.strptime(q, ['%m','%d','%Y'].join(sep)) rescue nil } || (Date.parse(q) rescue nil)
    if date
      dates = [:year, :month, :day].inject(Array.wrap(date)) {|d,t| d + [date - 1.send(t), date + 1.send(t)] }
      where(Array.new(dates.size) { "dob  = ? " }.join("OR "), *dates)
    else
      q_reg = "%#{q}%"
      joins(:phones).where("first LIKE ? OR middle LIKE ? OR last LIKE ? OR phones.number LIKE ? OR email LIKE ?",
      q_reg, q_reg, q_reg, q_reg, q_reg)
    end
  }

  def admin_or_staff?
    self.staff? || self.admin?
  end

  attr_accessor :edited_by_staff

  def timeout_in
    admin_or_staff? ? 10.years : 10.minutes
  end

  def email_required?
    !edited_by_staff
  end

  def password_required?
    !edited_by_staff
  end

  def display
    d = ""
    d += "#{first} " if first
    d += "#{middle} " if middle
    d += last || ""
    d.blank? ? "(No Name)" : d
  end

  def reverse_display
    d = ""
    d += "#{last}, " if last
    d += "#{first} " if first
    d += middle || ""
    d.blank? ? "(No Name)" : d
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!, except: [:profile, :update_profile]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @referer = request.env['HTTP_X_XHR_REFERER'] || request.env['HTTP_REFERER']
  end

  # GET /users/profile
  # GET /users/profile.json
  def profile
    @user = current_user
    render :show
  end

  def update_profile
    @user = current_user
    update
  end

  def create
    @user = User.new(user_params)
    @user.edited_by_staff = current_user.admin_or_staff? # Just to be safe
    respond_to do |format|
      if @user.save
        format.json { render :show, status: :ok, location: admin_user_url(@user)}
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user.edited_by_staff = current_user.admin_or_staff?
    respond_to do |format|
      if (current_user.patient? || current_user == @user) && user_params[:current_password].blank?
        @user.errors.add(:current_password, 'cannot be blank')
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      elsif ((current_user.patient? || current_user == @user) && @user.update_with_password(user_params)) || (current_user.admin_or_staff? && current_user != @user && @user.update_without_password(user_params))
        if current_user.admin_or_staff?
          format.html { redirect_to params[:referer] || admin_user_url(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: admin_user_url(@user) }
        else
          format.html { redirect_to root_path, notice: 'Your profile was successfully updated.' }
          format.json { render :show, status: :ok, location: profile_url }
        end
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.includes(:phones, :addresses).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if current_user.admin_or_staff? && @user != current_user
        params.require(:user).permit(:email, :gender, :dob, :password, :password_confirmation, :business, :first, :middle, :last, phones_attributes: [:id, :kind, :country, :number, :extension, :type, :_destroy], addresses_attributes: [:id, :street, :apt, :postcode, :city, :state, :country])
      elsif (current_user.patient? && action_name == 'update_profile') || @user == current_user
        params.require(:user).permit(:email, :current_password, :gender, :dob, :password, :password_confirmation, :business, :first, :middle, :last, phones_attributes: [:id, :kind, :country, :number, :extension, :type, :_destroy], addresses_attributes: [:id, :street, :apt, :postcode, :city, :state, :country])
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_fields.html.erb
<div class="form-group form-group-lg">
  <%= f.label :street, 'Address', class: 'col-sm-2 control-label' %>
  <%= f.hidden_field :id %>
  <div class="col-sm-9">
    <%= f.text_field :street, class: 'form-control', placeholder: '123 Some Pl.' %>
  </div>
  <% if defined?(render_add) && render_add %>
    <div class="col-sm-1">
      <%= link_to_add_fields parent_f, :addresses, class: "btn btn-default btn-lg", title: "Add address", selector: '$(this).closest(".selector-addresses").siblings(".selector-addresses").andSelf().last()', wrap: '<div class="selector-addresses"/>', partial: 'users/address_fields' do %>
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
      <% end %>
    </div>
  <% end %>
  <% if defined?(render_delete) && render_delete || !defined?(render_delete) %>
    <div class="col-sm-1">
      <%= link_to_destroy_fields f, selector: '$(this).closest(".selector-addresses")', class: 'btn btn-danger btn-lg' do %>
        <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"/>
      <% end %>
    </div>
  <% end %>
</div>
<div class="form-group form-group-lg">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.text_field :apt, class: 'form-control', placeholder: 'Apt #456 (optional)' %>
  </div>
</div>
<div class="form-group form-group-lg">
  <div class="col-sm-offset-2 col-sm-2">
    <%= f.text_field :postcode, class: 'form-control', placeholder: 'Zip/Postcode' %>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :city, class: 'form-control', placeholder: 'City' %>
  </div>
  <div class="col-sm-2">
    <%= f.text_field :state, class: 'form-control', placeholder: 'State/Province' %>
  </div>
  <div class="col-sm-2">
    <%= f.text_field :country, class: 'form-control', placeholder: 'Country' %>
  </div>
</div>

app/views/users/_address_group.html.erb
<% f.object.addresses.each.with_index do |address, index| %>
  <%= f.fields_for :addresses, address do |a| %>
    <div class="selector-addresses">
      <%= render partial: 'users/address_fields', locals: {f: a, parent_f: f, render_delete: index != 0, render_add: index == 0} %>
    </div>
  <% end %>
<% end %>

app/views/users/_phone_fields.html.erb
<%= f.label :number, 'Phone', class: 'col-sm-2 control-label' %>
<%= f.hidden_field :id %>
<div class="col-sm-2">
  <%= f.select :kind, options_for_select(Phone.kinds.map {|label,i| [label.titleize, label]}, f.object.kind), {}, class: 'form-control' %>
</div>
<div class="col-sm-1">
  <%= f.text_field :country, class: 'form-control', value: f.object.country || 1 %>
</div>
<div class="col-sm-4">
  <%= f.text_field :number, class: 'form-control', placeholder: 'Phone number' %>
</div>
<div class="col-sm-2">
  <div class="input-group">
    <span class="input-group-addon">x</span>
    <%= f.text_field :extension, class: 'form-control', placeholder: 'Extension' %>
  </div>
</div>
<% if defined?(render_delete) && render_delete || !defined?(render_delete) %>
  <div class="col-sm-1">
    <%= link_to_destroy_fields f, selector: '$(this).closest(".form-group")', class: 'btn btn-danger btn-lg' do %>
      <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"/>
    <% end %>
  </div>
<% end %>

app/views/users/_phone_group.html.erb
<% f.object.phones.each.with_index do |phone, index| %>
  <%= f.fields_for :phones, phone do |p| %>
    <div class="form-group form-group-lg selector-phones">
      <%= render partial: 'users/phone_fields', locals: {f: p, render_delete: index != 0} %>
      <% if index == 0 %>
        <div class="col-sm-1">
          <%= link_to_add_fields f, :phones, class: "btn btn-default btn-lg", title: "Add phone", selector: '$(this).closest(".selector-phones").siblings(".selector-phones").andSelf().last()', wrap: '<div class="form-group form-group-lg selector-phones"/>', partial: 'users/phone_fields' do %>
          <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_user_row.html.erb
<tr>
  <td><%= link_to user.reverse_display, admin_user_path(user) %></td>
  <td><%= mail_to(user.email) %></td>
  <td><%= user.dob %></td>
  <% phone = user.phones.first %>
  <td><%= number_to_phone(phone.number, area_code: true, country_code: phone.country, extension: phone.extension) %></td>
  <td><%= link_to content_tag(:i, 'Edit', class: 'glyphicon glyphicon-edit'), edit_admin_user_path(user) %></td>
  <td><%= link_to content_tag(:i, 'Remove', class: 'glyphicon glyphicon-trash'), admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/users/edit.html.erb
<h2>Edit <%= current_user == @user ? 'Your Profile' : 'Patient' %></h2>
<% url = current_user == @user ? update_profile_path : admin_user_path(@user) %>
<%= form_for(@user, url: url, html: { method: :put, class: 'form-horizontal'}) do |f| %>
  <%= devise_error_messages! %>

  <%= render 'devise/registrations/form', {f: f} %>
  <%= hidden_field_tag :referer, @referer %>
  <div class="form-group form-group-lg">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Update", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

<h3>Cancel <%= current_user == @user ? 'my account' : 'patient account' %></h3>

<div class="well">
  <% if current_user.admin_or_staff? && @user != current_user %>
    <%= button_to "Remove patient", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>
  <% else %>
    Unhappy?
    <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Listing users</h1>
  </div>
  <div class="col-md-4">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

<div class="row">
  <%= form_tag admin_users_path, method: :get, remote: true, format: :js, id: 'user-search-form' do %>
    <div class="col-lg-6">
      <div class="input-group">
        <%= text_field_tag :search, '', class: 'form-control', placeholder: 'Name, email, phone, date of birth', onkeyup: "javascript:$('#user-search-form').submit()" %>
        <span class="input-group-btn">
          <%= button_tag class: 'btn btn-default glyphicon glyphicon-search' do %>
            <input type="submit" value="submit" class="hidden" />
          <% end %>
        </span>
      </div>
    </div>
    <div class="col-md-6">
    </div>
  <% end %>
</div>
<table id="users-table" class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date of Birth</th>
      <th>Phone</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <%= render 'user_row', user: user %>
    <% end %>
  </tbody>
</table>

app/views/users/index.js.erb
$('#users-table tbody').children().remove();
<% @users.each do |user| %>
  $('#users-table tbody').append("<%= escape_javascript(render 'user_row', user: user) %>");
<% end %>

app/views/users/show.html.erb
<%= render template: 'users/edit' %>